version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/" # Assuming package.json is in the root
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
