name: CI Testing - Windows
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests on ${{ matrix.os }} Node ${{ matrix.node }} # Updated job name for clarity
    strategy:
      matrix:
        node: [22]
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flvtool2 (Windows)
        shell: pwsh # Explicitly use PowerShell, though it's default on Windows
        run: |
          curl -L -o flvtool2.exe https://github.com/unnu/flvtool2/raw/master/flvtool2.exe
          Add-Content -Path $env:GITHUB_PATH -Value "${{ github.workspace }}"
      - name: Setup FFmpeg action
        uses: thedave42/setup-ffmpeg@main
        with:
          version: master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Upload test results artifact # Changed from 'Upload test results to GitHub Artifacts'
        if: always() # Ensure artifact is uploaded even if tests fail or job is cancelled
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.node }} # Unique artifact name per job
          path: test-results.xml
          retention-days: 1 # Optional: keep artifacts for a short period

  publish-all-results:
    name: Publish all test results
    runs-on: ubuntu-latest
    needs: test # Depends on the 'test' job (all matrix instances)
    if: always() # Run this job even if test jobs fail, to publish what we have
    steps:
      - name: Download all test results artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-test-results # All artifacts will be downloaded here
                                 # Each artifact in its own subdirectory, e.g., all-test-results/test-results-ubuntu-latest-node-22/test-results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: all-test-results/**/test-results.xml # Glob pattern to find all test-results.xml files

