name: CI Testing
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        node: [22]
        os: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flvtool2 (Linux/macOS)
        if: runner.os != 'Windows'
        run: sudo gem install flvtool2
      - name: Install flvtool2 (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -L -o flvtool2.exe https://github.com/unnu/flvtool2/raw/master/flvtool2.exe
          echo "${{ github.workspace }}\flvtool2.exe" >> $GITHUB_PATH
      - name: Setup FFmpeg action
        uses: AnimMouse/setup-ffmpeg@v1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test 
      - name: Upload test results to GitHub Artifacts
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node }}
          path: test-results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            test-results.xml

