name: CI Testing
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flvtool2
        run: sudo gem install flvtool2
      - name: Setup FFmpeg action
        uses: AnimMouse/setup-ffmpeg@v1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Generate coverage report
        run: yarn coverage
      - name: Upload coverage to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-node-${{ matrix.node }}
          path: coverage/lcov.info

